Add search for ExpenseCategory to NetSuite Records
mavenlink-solutions/netsuite pull request #5
Opened 2016-12-07 19:02 UTC by azellsworth

- pulls in all categories from NetSuite

@ahuth @shirish-pampoorickal @AnnaMhairi

2016-12-08 01:00 UTC, shirish-pampoorickal requested changes
I think we are missing a few things

2016-12-08 01:00 UTC, shirish-pampoorickal commented on lib/netsuite/records/expense_category.rb
> +      actions :search
Can you add the reference link to be consistent with other record files?
https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2014_1/script/record/expensecategory.html

2016-12-08 01:00 UTC, shirish-pampoorickal commented on lib/netsuite/records/expense_category.rb
> +      actions :search
Is there a reason we are not adding the standard actions?
```
actions :get, :get_list, :add, :delete, :search, :update, :upsert
```

2016-12-08 01:00 UTC, shirish-pampoorickal commented on lib/netsuite/records/expense_category.rb
> +    end
Also, seems like any record with search action has the follow methods:
```
     # Copied over from lib/netsuite/records/expense_report.rb

      # seems like this is necessary
      def self.search_class_name
        "Transaction"
      end

      # not sure if this is needed
      def self.search_class_namespace
        "tranSales"
      end
```

2016-12-08 02:04 UTC, azellsworth commented on lib/netsuite/records/expense_category.rb
> +      actions :search
We only know the search works at this point... I guess fine to add the others, we just haven't made sure they worked.

2016-12-09 19:38 UTC, azellsworth commented on lib/netsuite/records/expense_category.rb
> +      actions :search
Done

2016-12-09 19:49 UTC, ahuth approved these changes

2016-12-09 19:51 UTC, azellsworth commented on lib/netsuite/records/expense_category.rb
> +    end
Done

2016-12-09 19:52 UTC, azellsworth commented
@shirish-pampoorickal comments addressed

2016-12-09 19:57 UTC, shirish-pampoorickal approved these changes
We should look into adding the missing standard actions in a later pull request. Other than that Code LGTM!

2016-12-09 19:58 UTC, merged